version: '3.8'

services:
  django_api:
    build: ./api_news
    ports:
      - "8000:8000"
    networks:
      - my_network

  front_end:
    build: ./front-end
    volumes:
      - ./front-end:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - django_api
    networks:
      - my_network

networks:
  my_network:
